"""remove name_ja column

Revision ID: d0ed61cf5b65
Revises: 60ab130e62c5
Create Date: 2025-04-12 13:50:04.774749+00:00

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d0ed61cf5b65"
down_revision = "60ab130e62c5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("card", "name_ja")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "card",
        sa.Column("name_ja", sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
